// Fallback data snapshot generated by scripts/snapshot-qef-defaults.js.
// Re-run the script after Google Sheet changes that should update API fallback content.
window.QEF_SITE_CONFIG = {
  "schoolNameZh": "香海正覺蓮社佛教普光學校",
  "schoolNameEn": "HHCKLA Buddhist Po Kwong School",
  "siteTitle": "普光高中教育︰實境教學",
  "siteSubtitle": "以真實情境連繫課程、職場與生活，讓學生在參與中建立能力與信心。",
  "planTitle": "創設實況學習場地（咖啡店），提升學生生涯規劃及職前培訓，強化獨立生活能力",
  "footerText": "QEF 計劃公開介紹網站",
  "apiBaseUrl": "https://script.google.com/macros/s/AKfycbyUHXRA6cHe3j2qaPsjl5sz3W0lUyoemJST2eXeRK83Aj2wUaMS8nWH2UJwQTWmAvNh/exec",
  "apiMode": "jsonp",
  "apiTimeoutMs": 90000,
  "useSampleDataWhenApiMissing": true,
  "googleSheet": {
    "spreadsheetId": "1hplWteuEJGSkNrn0S2AyzHoDxw_DJK_DW_XRyHL4FQM",
    "spreadsheetUrl": "https://docs.google.com/spreadsheets/d/1hplWteuEJGSkNrn0S2AyzHoDxw_DJK_DW_XRyHL4FQM/edit",
    "tabs": [
      "QEF_Settings",
      "QEF_Pages",
      "QEF_Metrics"
    ]
  },
  "googleDrive": {
    "photoRootFolderId": "1wibEm9nltRtrFjoLIN0yuKWYUwVF5MuB",
    "photoRootFolderUrl": "https://drive.google.com/drive/folders/1wibEm9nltRtrFjoLIN0yuKWYUwVF5MuB"
  },
  "sections": [
    {
      "id": "home",
      "title": "計劃簡介",
      "navTitle": "計劃簡介",
      "category": "計劃簡介",
      "order": 1,
      "date": "",
      "summary": "本計劃以實況咖啡店為學習場地，連繫課程、生涯規劃與獨立生活訓練。",
      "body": "本計劃以實況咖啡店為學習場地，連繫課程、生涯規劃與獨立生活訓練。\n\n計劃透過校本高中課程及其他學習經歷，讓學生在餐飲製作、服務接待、店舖營運、社區探索及工作體驗中學習。網站將按不同部分整理安排、相片及簡介，展示學生在真實情境中的成長歷程。",
      "imageId": "1eXs9eZa7L3qIhpxNkQ0eJMk9INlFS2w2",
      "folderId": "",
      "published": true
    },
    {
      "id": "learning-space",
      "title": "實況學習場地（咖啡店）",
      "navTitle": "實況咖啡店",
      "category": "實況咖啡店",
      "order": 2,
      "date": "",
      "summary": "校內設置實況學習場地，支援餐飲製作、接待服務、零售營運及場地管理訓練。",
      "body": "校內設置實況學習場地，支援餐飲製作、接待服務、零售營運及場地管理訓練。\n\n實況咖啡店模擬真實工作場景，學生可在安全而具結構的環境中學習服務流程、職安健、溝通協作及顧客服務，逐步建立工作習慣和自信。",
      "imageId": "1dU1jgmIKlPkJdtbpR7G4J7C2ZGdGH63m",
      "folderId": "",
      "published": true
    },
    {
      "id": "curriculum",
      "title": "課程與學習安排",
      "navTitle": "課程安排",
      "category": "課程安排",
      "order": 3,
      "date": "",
      "summary": "計劃結合高中校本課程、其他學習經歷及跨科協作，讓學生在真實任務中實踐所學。",
      "body": "計劃結合高中校本課程、其他學習經歷及跨科協作，讓學生在真實任務中實踐所學。\n\n課程涵蓋餐飲製作、服務接待、店舖營運、藝術發展、社區探索、工作體驗及獨立生活等範疇，並按學生能力設計輕度及中度課程路徑。",
      "imageId": "19Kcdhglu9XrP-4OaJQ_JcADQO5xDoWx9",
      "folderId": "",
      "published": true
    },
    {
      "id": "digital-retail",
      "title": "電子點餐與店舖營運",
      "navTitle": "電子營運",
      "category": "電子營運",
      "order": 4,
      "date": "",
      "summary": "學生透過電子點餐、收銀、貨品管理及推廣任務，認識現代店舖營運。",
      "body": "學生透過電子點餐、收銀、貨品管理及推廣任務，認識現代店舖營運。\n\n電子營運元素讓學生接觸數碼工具、顧客流程及後勤管理，並把語文、數學、資訊科技與生活技能連繫到真實服務場景。",
      "imageId": "1sscgz1N9nbxrjwJrWpZ41V5T8HzXj-he",
      "folderId": "",
      "published": true
    },
    {
      "id": "portfolio",
      "title": "生涯規劃之旅記錄冊",
      "navTitle": "學習歷程",
      "category": "學習歷程",
      "order": 5,
      "date": "",
      "summary": "學生以記錄冊整理課程成果、工作體驗、反思及個人成長證據。",
      "body": "學生以記錄冊整理課程成果、工作體驗、反思及個人成長證據。\n\n記錄冊支援學生回顧學習歷程、整理能力表現和訂立下一步目標，亦方便教師、家長及支援人員了解學生在生涯規劃及獨立生活方面的進展。",
      "imageId": "1Ns-Yoz1VL-KLu1ye6iJfYxh2gmVUzFfG",
      "folderId": "",
      "published": true
    },
    {
      "id": "community",
      "title": "社區連繫與服務",
      "navTitle": "社區連繫",
      "category": "社區連繫",
      "order": 6,
      "date": "",
      "summary": "計劃把校內學習延伸至社區服務及分享活動，促進學生參與和歸屬感。",
      "body": "計劃把校內學習延伸至社區服務及分享活動，促進學生參與和歸屬感。\n\n透過社區探索、服務體驗及校外連繫，學生把課堂技能應用於日常生活和公共情境，建立責任感、溝通能力及正向自我形象。",
      "imageId": "1GmGfaU9qwgJgaiclHYWHYH-oUrxHGj2z",
      "folderId": "",
      "published": true
    },
    {
      "id": "outcomes",
      "title": "預期成效與展望",
      "navTitle": "預期成效",
      "category": "預期成效",
      "order": 7,
      "date": "",
      "summary": "計劃期望提升學生職前能力、獨立生活能力及生涯規劃意識。",
      "body": "計劃期望提升學生職前能力、獨立生活能力及生涯規劃意識。\n\n透過課程、場地、記錄冊及家校社合作，計劃將逐步累積可展示、可延續的學習成果，並支援學校持續發展多元化職業及生活技能教育。",
      "imageId": "1Tr7Yhz6STfJKUgNyOlXzFg5HZt95H3VI",
      "folderId": "",
      "published": true
    },
    {
      "id": "light-food-prep",
      "title": "輕度課程：基礎餐飲製作",
      "navTitle": "餐飲製作",
      "category": "課程內容",
      "order": 20,
      "date": "",
      "summary": "學生在實況咖啡店中學習基礎餐飲製作、水吧運作及食材處理。",
      "body": "學生在實況咖啡店中學習基礎餐飲製作、水吧運作及食材處理。\n\n透過恆常及密集訓練，學生認識職安健、衛生操守、餐單設計、輕食及飲品製作，並在真實服務情境中累積生活及職場相關技能。",
      "imageId": "https://drive.google.com/open?id=19Kcdhglu9XrP-4OaJQ_JcADQO5xDoWx9&usp=drive_fs",
      "folderId": "1Z4c6iIMyQKrkiOZqGessjlhyvkfFEAoJ",
      "published": true
    },
    {
      "id": "light-catering-cleaning",
      "title": "輕度課程：基礎餐飲服務及清潔",
      "navTitle": "餐飲服務",
      "category": "課程內容",
      "order": 21,
      "date": "",
      "summary": "學生學習餐飲接待、基本侍應款待、餐桌禮儀及店面清潔。",
      "body": "學生學習餐飲接待、基本侍應款待、餐桌禮儀及店面清潔。\n\n課程讓學生在接待、送餐、整理餐具及維持環境整潔等任務中，培養溝通、協作、自理和良好工作態度。",
      "imageId": "",
      "folderId": "1RPFBMNjntlUZxeZdTNzH1g7PyDuwKs_Z",
      "published": true
    },
    {
      "id": "light-shop-operation",
      "title": "輕度課程：基礎店鋪營運",
      "navTitle": "店鋪營運",
      "category": "課程內容",
      "order": 22,
      "date": "",
      "summary": "學生參與店鋪營運、貨品陳列、採購及推廣等工作流程。",
      "body": "學生參與店鋪營運、貨品陳列、採購及推廣等工作流程。\n\n學生在實務任務中學習點貨、補貨、陳列、宣傳及簡單營運紀錄，理解店鋪運作背後的分工與責任。",
      "imageId": "",
      "folderId": "16wLHuH2sRdQ_bQT_aAT-1TxAbQx95He0",
      "published": true
    },
    {
      "id": "light-workplace-life",
      "title": "輕度課程：職場生活",
      "navTitle": "職場生活",
      "category": "課程內容",
      "order": 23,
      "date": "",
      "summary": "學生認識職場常規、工作禮儀、溝通技巧及日常工作態度。",
      "body": "學生認識職場常規、工作禮儀、溝通技巧及日常工作態度。\n\n課程協助學生建立守時、服從指示、整理儀容、合作和完成任務等基礎職場習慣，為日後工作體驗及銜接作準備。",
      "imageId": "",
      "folderId": "19mBb8JzrUZFFlJVc0ii61i-SOjpGz59L",
      "published": true
    },
    {
      "id": "light-art-development",
      "title": "輕度課程：藝術發展",
      "navTitle": "藝術發展",
      "category": "課程內容",
      "order": 24,
      "date": "",
      "summary": "學生透過藝術創作、展示及手作活動發展表達能力和專注力。",
      "body": "學生透過藝術創作、展示及手作活動發展表達能力和專注力。\n\n藝術課程可與店舖佈置、節慶展示及產品包裝連繫，讓學生在美感、手眼協調、創意表達及團隊協作中建立成功經驗。",
      "imageId": "",
      "folderId": "1lAKv8doW_-WeDqJNG2L30SuGxGohQwY3",
      "published": true
    },
    {
      "id": "light-community-exploration",
      "title": "輕度課程：社區探索",
      "navTitle": "社區探索",
      "category": "課程內容",
      "order": 25,
      "date": "",
      "summary": "學生透過社區參觀及生活任務，連繫校內學習與真實生活。",
      "body": "學生透過社區參觀及生活任務，連繫校內學習與真實生活。\n\n課程引導學生觀察社區設施、認識服務流程及練習外出禮儀，提升生活適應、社交溝通和安全意識。",
      "imageId": "",
      "folderId": "1U_T0preTA6HO_nDOfl0DT-H4H8HF-009",
      "published": true
    },
    {
      "id": "light-work-experience",
      "title": "輕度課程：工作體驗",
      "navTitle": "工作體驗",
      "category": "課程內容",
      "order": 26,
      "date": "",
      "summary": "學生在校內外工作任務中嘗試不同職務，理解工作要求。",
      "body": "學生在校內外工作任務中嘗試不同職務，理解工作要求。\n\n工作體驗讓學生把課堂所學應用於真實或模擬工作場景，累積任務完成、溝通合作及自我反思經驗。",
      "imageId": "",
      "folderId": "1ojhiKlfHiULes0ZhlEgLhhOwX9eTFtdS",
      "published": true
    },
    {
      "id": "moderate-cleaning",
      "title": "中度課程：清潔訓練",
      "navTitle": "清潔訓練",
      "category": "課程內容",
      "order": 27,
      "date": "",
      "summary": "學生學習基本清潔程序、工具使用及環境整理。",
      "body": "學生學習基本清潔程序、工具使用及環境整理。\n\n透過結構化清潔訓練，學生掌握步驟、次序、安全和衞生要求，建立照顧環境及完成工作任務的能力。",
      "imageId": "",
      "folderId": "1F-sl3VMwI0mFbL7n1nAALn2Lpbhn7Ao1",
      "published": true
    },
    {
      "id": "moderate-planting",
      "title": "中度課程：種植訓練",
      "navTitle": "種植訓練",
      "category": "課程內容",
      "order": 28,
      "date": "",
      "summary": "學生透過種植活動學習照顧植物、觀察成長及維持環境。",
      "body": "學生透過種植活動學習照顧植物、觀察成長及維持環境。\n\n種植訓練提供重複而具生活感的任務，學生在澆水、整理、觀察及簡單記錄中培養責任感和持續參與。",
      "imageId": "",
      "folderId": "1dSaoaYReyetCVUaVt4aMw9ZjURC7t7s1",
      "published": true
    },
    {
      "id": "moderate-art-development",
      "title": "中度課程：藝術發展",
      "navTitle": "藝術發展",
      "category": "課程內容",
      "order": 29,
      "date": "",
      "summary": "學生透過藝術媒介發展感官探索、情緒表達及創作經驗。",
      "body": "學生透過藝術媒介發展感官探索、情緒表達及創作經驗。\n\n課程以可操作、可展示的活動支援學生參與，並連繫校園環境佈置、作品分享及節慶活動，建立自信和投入感。",
      "imageId": "",
      "folderId": "1UZ30B-FKIRd2jnbfcne-YghOYRBMRg0y",
      "published": true
    },
    {
      "id": "moderate-community-exploration",
      "title": "中度課程：社區探索",
      "navTitle": "社區探索",
      "category": "課程內容",
      "order": 30,
      "date": "",
      "summary": "學生在支援下認識社區設施、外出流程及生活情境。",
      "body": "學生在支援下認識社區設施、外出流程及生活情境。\n\n課程重視安全、觀察、簡單選擇及溝通表達，讓學生逐步把校內訓練連繫到社區生活。",
      "imageId": "",
      "folderId": "1jdRjNQSz1vyha90W_2VCnH7njVbU7Wc3",
      "published": true
    },
    {
      "id": "moderate-independent-living",
      "title": "中度課程：獨立生活",
      "navTitle": "獨立生活",
      "category": "課程內容",
      "order": 31,
      "date": "",
      "summary": "學生學習日常自理、家居生活及簡單生活決策。",
      "body": "學生學習日常自理、家居生活及簡單生活決策。\n\n獨立生活課程涵蓋整理、烹調前準備、個人照顧及生活安全等內容，協助學生提升日常生活參與及自立能力。",
      "imageId": "",
      "folderId": "1HFxqP472SxViV8YGw6XihKimh0DLu1PL",
      "published": true
    },
    {
      "id": "moderate-work-experience",
      "title": "中度課程：工作體驗",
      "navTitle": "工作體驗",
      "category": "課程內容",
      "order": 32,
      "date": "",
      "summary": "學生透過合適的工作任務建立參與感、專注力和完成任務能力。",
      "body": "學生透過合適的工作任務建立參與感、專注力和完成任務能力。\n\n工作體驗以小步驟和清晰支援協助學生理解工作流程，讓學生在可達成的任務中累積成功經驗和正向工作態度。",
      "imageId": "",
      "folderId": "16cdQHWPpXYU81Lj8OdpeF3TCiXLTWOft",
      "published": true
    },
    {
      "id": "moderate-personal-growth",
      "title": "中度課程：個人成長",
      "navTitle": "個人成長",
      "category": "課程內容",
      "order": 33,
      "date": "",
      "summary": "學生透過團體活動、生活任務及反思建立自我認識和正面情緒。",
      "body": "學生透過團體活動、生活任務及反思建立自我認識和正面情緒。\n\n個人成長活動支援學生認識自己、表達需要、參與群體及建立良好生活習慣，為學習、生活及社交發展提供基礎。",
      "imageId": "",
      "folderId": "1OPw3o4a2evYOrKW-Inx1E7n96QCyaQKl",
      "published": true
    }
  ],
  "metrics": [
    {
      "id": "students",
      "label": "學生",
      "value": "100 人",
      "detail": "中四至中六直接受惠學生",
      "order": 1,
      "published": true
    },
    {
      "id": "teachers",
      "label": "教師",
      "value": "70 人",
      "detail": "共同備課、課程實踐及專業分享",
      "order": 2,
      "published": true
    },
    {
      "id": "parents",
      "label": "家長",
      "value": "100 人",
      "detail": "了解學生學習歷程及生涯規劃方向",
      "order": 3,
      "published": true
    },
    {
      "id": "period",
      "label": "推行時期",
      "value": "09/2024 - 07/2026",
      "detail": "按 QEF 計劃節錄資料建立",
      "order": 4,
      "published": true
    }
  ],
  "photos": [
    {
      "id": "light-food-prep-1owYmwqSoHECtJ_xO8BifJthqkBP9lRQF",
      "pageId": "light-food-prep",
      "imageId": "1owYmwqSoHECtJ_xO8BifJthqkBP9lRQF",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1owYmwqSoHECtJ_xO8BifJthqkBP9lRQF&sz=w800",
      "caption": "我終於成功拉花了！",
      "order": 1000,
      "published": true
    },
    {
      "id": "light-food-prep-19Kcdhglu9XrP-4OaJQ_JcADQO5xDoWx9",
      "pageId": "light-food-prep",
      "imageId": "19Kcdhglu9XrP-4OaJQ_JcADQO5xDoWx9",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=19Kcdhglu9XrP-4OaJQ_JcADQO5xDoWx9&sz=w800",
      "caption": "感謝教職員光顧尚cafe，讓學生順利進行餐飲業實習！",
      "order": 1001,
      "published": true
    },
    {
      "id": "light-food-prep-13iGhhGvdAjawOwwWEgxw8q15_1pFjQDp",
      "pageId": "light-food-prep",
      "imageId": "13iGhhGvdAjawOwwWEgxw8q15_1pFjQDp",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=13iGhhGvdAjawOwwWEgxw8q15_1pFjQDp&sz=w800",
      "caption": "高水準午餐：低糖芝麻豆奶配冬蔭功大蝦意粉，令人食指大動！",
      "order": 1002,
      "published": true
    },
    {
      "id": "light-food-prep-1TRFSQ47kUefoZGrIDc4D0TY1KZT6csm3",
      "pageId": "light-food-prep",
      "imageId": "1TRFSQ47kUefoZGrIDc4D0TY1KZT6csm3",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1TRFSQ47kUefoZGrIDc4D0TY1KZT6csm3&sz=w800",
      "caption": "自家種香草，大派用場！",
      "order": 1003,
      "published": true
    },
    {
      "id": "light-food-prep-1eXs9eZa7L3qIhpxNkQ0eJMk9INlFS2w2",
      "pageId": "light-food-prep",
      "imageId": "1eXs9eZa7L3qIhpxNkQ0eJMk9INlFS2w2",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1eXs9eZa7L3qIhpxNkQ0eJMk9INlFS2w2&sz=w800",
      "caption": "同學們專注地為嘉賓沖調咖啡飲品。",
      "order": 1004,
      "published": true
    },
    {
      "id": "light-food-prep-1ou3Z4SfUpdRCX4cilVjX0Vi2OajepTz3",
      "pageId": "light-food-prep",
      "imageId": "1ou3Z4SfUpdRCX4cilVjX0Vi2OajepTz3",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1ou3Z4SfUpdRCX4cilVjX0Vi2OajepTz3&sz=w800",
      "caption": "招牌焦糖凍咖啡配自家製香橙、百香果素食芝士蛋糕，令人一試難忘。",
      "order": 1005,
      "published": true
    },
    {
      "id": "light-food-prep-1oo0QFcwsVSJrbBUD0sToObjghBwZQ1Be",
      "pageId": "light-food-prep",
      "imageId": "1oo0QFcwsVSJrbBUD0sToObjghBwZQ1Be",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1oo0QFcwsVSJrbBUD0sToObjghBwZQ1Be&sz=w800",
      "caption": "同學們熱烈地招待到尚cafe參觀的嘉賓。",
      "order": 1006,
      "published": true
    },
    {
      "id": "light-food-prep-1km3b2CJIOiMrK7yZC1hBpfcQReuwmycI",
      "pageId": "light-food-prep",
      "imageId": "1km3b2CJIOiMrK7yZC1hBpfcQReuwmycI",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1km3b2CJIOiMrK7yZC1hBpfcQReuwmycI&sz=w800",
      "caption": "同學們專心地調製香橙tonic咖啡。",
      "order": 1007,
      "published": true
    },
    {
      "id": "light-food-prep-1icObF7BFseBwN79oqI8NWS98wLmOslVO",
      "pageId": "light-food-prep",
      "imageId": "1icObF7BFseBwN79oqI8NWS98wLmOslVO",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1icObF7BFseBwN79oqI8NWS98wLmOslVO&sz=w800",
      "caption": "令人無法抗拒的早餐組合。",
      "order": 1008,
      "published": true
    },
    {
      "id": "light-food-prep-16UbFHfVfntiC5keUH9OL_Sload1xAbm-",
      "pageId": "light-food-prep",
      "imageId": "16UbFHfVfntiC5keUH9OL_Sload1xAbm-",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=16UbFHfVfntiC5keUH9OL_Sload1xAbm-&sz=w800",
      "caption": "當熱呼呼的燒賣遇上冰冷的香橙tonic咖啡，味道會是如何？",
      "order": 1009,
      "published": true
    },
    {
      "id": "light-food-prep-1uougf220pvfmcb64iPwq4xSUWv70mk0k",
      "pageId": "light-food-prep",
      "imageId": "1uougf220pvfmcb64iPwq4xSUWv70mk0k",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1uougf220pvfmcb64iPwq4xSUWv70mk0k&sz=w800",
      "caption": "辛勤的同學們，一早已為大家預備熱呼呼的燒賣！",
      "order": 1010,
      "published": true
    },
    {
      "id": "light-food-prep-1ZWNyzvAPI2dTXWDkDiLOyiTsQDruJSJ0",
      "pageId": "light-food-prep",
      "imageId": "1ZWNyzvAPI2dTXWDkDiLOyiTsQDruJSJ0",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1ZWNyzvAPI2dTXWDkDiLOyiTsQDruJSJ0&sz=w800",
      "caption": "專業咖啡師為大家提供優質燕麥拉花咖啡！",
      "order": 1011,
      "published": true
    },
    {
      "id": "light-catering-cleaning-1rg5juD2Iaxh6sq6tXtPpWItfp8pHNNyA",
      "pageId": "light-catering-cleaning",
      "imageId": "1rg5juD2Iaxh6sq6tXtPpWItfp8pHNNyA",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1rg5juD2Iaxh6sq6tXtPpWItfp8pHNNyA&sz=w800",
      "caption": "餐飲接待及清潔_鈞 (4)",
      "order": 1000,
      "published": true
    },
    {
      "id": "light-catering-cleaning-1udM1OZPjfz_LW7lemPzAAVfGieTquOaz",
      "pageId": "light-catering-cleaning",
      "imageId": "1udM1OZPjfz_LW7lemPzAAVfGieTquOaz",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1udM1OZPjfz_LW7lemPzAAVfGieTquOaz&sz=w800",
      "caption": "餐飲接待及清潔_鈞 (7)",
      "order": 1001,
      "published": true
    },
    {
      "id": "light-catering-cleaning-1m7ixz7lOSrZ9uY-xlCB57EWOO53Svap_",
      "pageId": "light-catering-cleaning",
      "imageId": "1m7ixz7lOSrZ9uY-xlCB57EWOO53Svap_",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1m7ixz7lOSrZ9uY-xlCB57EWOO53Svap_&sz=w800",
      "caption": "餐飲接待及清潔_鈞 (6)",
      "order": 1002,
      "published": true
    },
    {
      "id": "light-catering-cleaning-1n4z9kkhA_NLByF9qVDnYdb0YvBy4NfEY",
      "pageId": "light-catering-cleaning",
      "imageId": "1n4z9kkhA_NLByF9qVDnYdb0YvBy4NfEY",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1n4z9kkhA_NLByF9qVDnYdb0YvBy4NfEY&sz=w800",
      "caption": "餐飲接待及清潔_鈞 (5)",
      "order": 1003,
      "published": true
    },
    {
      "id": "light-catering-cleaning-1c-JgHsgouuPGugENKvEszQnlqBpbEgug",
      "pageId": "light-catering-cleaning",
      "imageId": "1c-JgHsgouuPGugENKvEszQnlqBpbEgug",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1c-JgHsgouuPGugENKvEszQnlqBpbEgug&sz=w800",
      "caption": "餐飲接待及清潔_鈞 (3)",
      "order": 1004,
      "published": true
    },
    {
      "id": "light-catering-cleaning-1MghLM0_eOp8ZqQy4D_yDpG5EWiN4YnHl",
      "pageId": "light-catering-cleaning",
      "imageId": "1MghLM0_eOp8ZqQy4D_yDpG5EWiN4YnHl",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1MghLM0_eOp8ZqQy4D_yDpG5EWiN4YnHl&sz=w800",
      "caption": "餐飲接待及清潔_鈞 (2)",
      "order": 1005,
      "published": true
    },
    {
      "id": "light-catering-cleaning-114UnQW6VucAPJi5uxeOh1pCfbaD0URfX",
      "pageId": "light-catering-cleaning",
      "imageId": "114UnQW6VucAPJi5uxeOh1pCfbaD0URfX",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=114UnQW6VucAPJi5uxeOh1pCfbaD0URfX&sz=w800",
      "caption": "餐飲接待及清潔_鈞 (1)",
      "order": 1006,
      "published": true
    },
    {
      "id": "light-shop-operation-1QyatUCD3iFJdfojm_l_zasEjRN2g0MiQ",
      "pageId": "light-shop-operation",
      "imageId": "1QyatUCD3iFJdfojm_l_zasEjRN2g0MiQ",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1QyatUCD3iFJdfojm_l_zasEjRN2g0MiQ&sz=w800",
      "caption": "IMG_1663",
      "order": 1000,
      "published": true
    },
    {
      "id": "light-shop-operation-1YMF6H7WkRr5EdPDp-G1wEdcAkpQwGYdJ",
      "pageId": "light-shop-operation",
      "imageId": "1YMF6H7WkRr5EdPDp-G1wEdcAkpQwGYdJ",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1YMF6H7WkRr5EdPDp-G1wEdcAkpQwGYdJ&sz=w800",
      "caption": "IMG_1664",
      "order": 1001,
      "published": true
    },
    {
      "id": "light-shop-operation-1i-ViI2GePpWVp1oFMmMxw-Tjr49nZjJS",
      "pageId": "light-shop-operation",
      "imageId": "1i-ViI2GePpWVp1oFMmMxw-Tjr49nZjJS",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1i-ViI2GePpWVp1oFMmMxw-Tjr49nZjJS&sz=w800",
      "caption": "IMG_7088",
      "order": 1002,
      "published": true
    },
    {
      "id": "light-shop-operation-1xzlCXj4Yc4FJptEV2ft2Q0V3BqW8C29Q",
      "pageId": "light-shop-operation",
      "imageId": "1xzlCXj4Yc4FJptEV2ft2Q0V3BqW8C29Q",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1xzlCXj4Yc4FJptEV2ft2Q0V3BqW8C29Q&sz=w800",
      "caption": "IMG_7080",
      "order": 1003,
      "published": true
    },
    {
      "id": "light-shop-operation-1DHsDgVVwEEtIO1dt0r0iPS5fwTALPBi9",
      "pageId": "light-shop-operation",
      "imageId": "1DHsDgVVwEEtIO1dt0r0iPS5fwTALPBi9",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1DHsDgVVwEEtIO1dt0r0iPS5fwTALPBi9&sz=w800",
      "caption": "IMG_7086",
      "order": 1004,
      "published": true
    },
    {
      "id": "light-shop-operation-19pZqjmT_M7WlCek4wNOCJzvtNSW-F7o9",
      "pageId": "light-shop-operation",
      "imageId": "19pZqjmT_M7WlCek4wNOCJzvtNSW-F7o9",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=19pZqjmT_M7WlCek4wNOCJzvtNSW-F7o9&sz=w800",
      "caption": "IMG_7083",
      "order": 1005,
      "published": true
    },
    {
      "id": "light-shop-operation-1wELsP8dKK9ngwRcogolkms9H00id6Kxa",
      "pageId": "light-shop-operation",
      "imageId": "1wELsP8dKK9ngwRcogolkms9H00id6Kxa",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1wELsP8dKK9ngwRcogolkms9H00id6Kxa&sz=w800",
      "caption": "IMG_7079",
      "order": 1006,
      "published": true
    },
    {
      "id": "light-shop-operation-1IUjI5W2vHLhu16iKrapPrljfZdoBnuZZ",
      "pageId": "light-shop-operation",
      "imageId": "1IUjI5W2vHLhu16iKrapPrljfZdoBnuZZ",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1IUjI5W2vHLhu16iKrapPrljfZdoBnuZZ&sz=w800",
      "caption": "IMG_6087",
      "order": 1007,
      "published": true
    },
    {
      "id": "light-workplace-life-1ZJaF70xgDIv3PUSixW7Ja3m7EOWVMqKn",
      "pageId": "light-workplace-life",
      "imageId": "1ZJaF70xgDIv3PUSixW7Ja3m7EOWVMqKn",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1ZJaF70xgDIv3PUSixW7Ja3m7EOWVMqKn&sz=w800",
      "caption": "職場生活_鈞 (4)",
      "order": 1000,
      "published": true
    },
    {
      "id": "light-workplace-life-1xaP4qcqa0b0liVJI55FNWj-PsyglOf7x",
      "pageId": "light-workplace-life",
      "imageId": "1xaP4qcqa0b0liVJI55FNWj-PsyglOf7x",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1xaP4qcqa0b0liVJI55FNWj-PsyglOf7x&sz=w800",
      "caption": "職場生活_鈞 (5)",
      "order": 1001,
      "published": true
    },
    {
      "id": "light-workplace-life-10QBfuYZBPU1a6Epc85rcgSB6nLwYMt9E",
      "pageId": "light-workplace-life",
      "imageId": "10QBfuYZBPU1a6Epc85rcgSB6nLwYMt9E",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=10QBfuYZBPU1a6Epc85rcgSB6nLwYMt9E&sz=w800",
      "caption": "職場生活_鈞 (3)",
      "order": 1002,
      "published": true
    },
    {
      "id": "light-workplace-life-1tE8nbsesRMUsEewP2h2lnLdNWg4C0KOW",
      "pageId": "light-workplace-life",
      "imageId": "1tE8nbsesRMUsEewP2h2lnLdNWg4C0KOW",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1tE8nbsesRMUsEewP2h2lnLdNWg4C0KOW&sz=w800",
      "caption": "職場生活_鈞 (2)",
      "order": 1003,
      "published": true
    },
    {
      "id": "light-workplace-life-1Y2WQ93PDjpKMlBwe0Qed_mnt8qhDFXwy",
      "pageId": "light-workplace-life",
      "imageId": "1Y2WQ93PDjpKMlBwe0Qed_mnt8qhDFXwy",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1Y2WQ93PDjpKMlBwe0Qed_mnt8qhDFXwy&sz=w800",
      "caption": "職場生活_鈞 (1)",
      "order": 1004,
      "published": true
    },
    {
      "id": "light-art-development-1HxpqnSEmcsdpswz2PSewLsFKJQywq_7L",
      "pageId": "light-art-development",
      "imageId": "1HxpqnSEmcsdpswz2PSewLsFKJQywq_7L",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1HxpqnSEmcsdpswz2PSewLsFKJQywq_7L&sz=w800",
      "caption": "IMG_8278",
      "order": 1000,
      "published": true
    },
    {
      "id": "light-art-development-1hvDBpFsYwJ8t6ou0p-e7rR5xi0D9TXZe",
      "pageId": "light-art-development",
      "imageId": "1hvDBpFsYwJ8t6ou0p-e7rR5xi0D9TXZe",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1hvDBpFsYwJ8t6ou0p-e7rR5xi0D9TXZe&sz=w800",
      "caption": "IMG_8281",
      "order": 1001,
      "published": true
    },
    {
      "id": "light-community-exploration-1GmGfaU9qwgJgaiclHYWHYH-oUrxHGj2z",
      "pageId": "light-community-exploration",
      "imageId": "1GmGfaU9qwgJgaiclHYWHYH-oUrxHGj2z",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1GmGfaU9qwgJgaiclHYWHYH-oUrxHGj2z&sz=w800",
      "caption": "學生享用西餐，大家都有注意餐飲禮儀，值得欣賞",
      "order": 1000,
      "published": true
    },
    {
      "id": "light-community-exploration-1Tq0aIieS3aXkgrVJYmXTRDEXAWacRRez",
      "pageId": "light-community-exploration",
      "imageId": "1Tq0aIieS3aXkgrVJYmXTRDEXAWacRRez",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1Tq0aIieS3aXkgrVJYmXTRDEXAWacRRez&sz=w800",
      "caption": "學生嘗試餐後自行返還餐具到店家指定收集處",
      "order": 1001,
      "published": true
    },
    {
      "id": "light-community-exploration-18GHsJo-7qhkkS9h3BW7izW-ozbSqyjjV",
      "pageId": "light-community-exploration",
      "imageId": "18GHsJo-7qhkkS9h3BW7izW-ozbSqyjjV",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=18GHsJo-7qhkkS9h3BW7izW-ozbSqyjjV&sz=w800",
      "caption": "學生們學習使用汽水機",
      "order": 1002,
      "published": true
    },
    {
      "id": "light-work-experience-1cxPwiEhYH3-RZHU1o88_vmODioUn5rgI",
      "pageId": "light-work-experience",
      "imageId": "1cxPwiEhYH3-RZHU1o88_vmODioUn5rgI",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1cxPwiEhYH3-RZHU1o88_vmODioUn5rgI&sz=w800",
      "caption": "學生們正專心製作洗髮皂，它是義賣時的重要產品",
      "order": 1000,
      "published": true
    },
    {
      "id": "light-work-experience-1weD-SuN123TB8mx_voQp_vH5uSNswjDC",
      "pageId": "light-work-experience",
      "imageId": "1weD-SuN123TB8mx_voQp_vH5uSNswjDC",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1weD-SuN123TB8mx_voQp_vH5uSNswjDC&sz=w800",
      "caption": "在職員用心教導下，學生學習如何裝飾咖啡",
      "order": 1001,
      "published": true
    },
    {
      "id": "light-work-experience-1bGEPhI4vVqPt_LudaBGYX0EQoAWANKvu",
      "pageId": "light-work-experience",
      "imageId": "1bGEPhI4vVqPt_LudaBGYX0EQoAWANKvu",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1bGEPhI4vVqPt_LudaBGYX0EQoAWANKvu&sz=w800",
      "caption": "學生專心地清潔奶壺，一點也不偷懶",
      "order": 1002,
      "published": true
    },
    {
      "id": "light-work-experience-1dU1jgmIKlPkJdtbpR7G4J7C2ZGdGH63m",
      "pageId": "light-work-experience",
      "imageId": "1dU1jgmIKlPkJdtbpR7G4J7C2ZGdGH63m",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1dU1jgmIKlPkJdtbpR7G4J7C2ZGdGH63m&sz=w800",
      "caption": "學生們到葵涌一間咖啡店進行實習",
      "order": 1003,
      "published": true
    },
    {
      "id": "light-work-experience-1kIjPPmcctIKDXKJRRop2MLxLpuhkilYl",
      "pageId": "light-work-experience",
      "imageId": "1kIjPPmcctIKDXKJRRop2MLxLpuhkilYl",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1kIjPPmcctIKDXKJRRop2MLxLpuhkilYl&sz=w800",
      "caption": "共融市集@愉景新城_學生向外界推廣自己設計的產品",
      "order": 1004,
      "published": true
    },
    {
      "id": "light-work-experience-1tycn5HO_Xgr4UtxyVM_WnxrjB4BY3Mvd",
      "pageId": "light-work-experience",
      "imageId": "1tycn5HO_Xgr4UtxyVM_WnxrjB4BY3Mvd",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1tycn5HO_Xgr4UtxyVM_WnxrjB4BY3Mvd&sz=w800",
      "caption": "DSC01000",
      "order": 1005,
      "published": true
    },
    {
      "id": "light-work-experience-1jZmBSLRu0-RmjtwjiU3KnbeNLcZQi89_",
      "pageId": "light-work-experience",
      "imageId": "1jZmBSLRu0-RmjtwjiU3KnbeNLcZQi89_",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1jZmBSLRu0-RmjtwjiU3KnbeNLcZQi89_&sz=w800",
      "caption": "第四屆潮州節@會展，學生們義賣自家製產品，學習管理攤位及招待客人，",
      "order": 1006,
      "published": true
    },
    {
      "id": "light-work-experience-10PycSL_zoUDVYG5Mc7ee-HNteL_TNtkL",
      "pageId": "light-work-experience",
      "imageId": "10PycSL_zoUDVYG5Mc7ee-HNteL_TNtkL",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=10PycSL_zoUDVYG5Mc7ee-HNteL_TNtkL&sz=w800",
      "caption": "IMG_5154",
      "order": 1007,
      "published": true
    },
    {
      "id": "light-work-experience-1l8VZXj_ifidjErEB2gJLRbWnDPmQPdNv",
      "pageId": "light-work-experience",
      "imageId": "1l8VZXj_ifidjErEB2gJLRbWnDPmQPdNv",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1l8VZXj_ifidjErEB2gJLRbWnDPmQPdNv&sz=w800",
      "caption": "IMG_5092",
      "order": 1008,
      "published": true
    },
    {
      "id": "light-work-experience-1sscgz1N9nbxrjwJrWpZ41V5T8HzXj-he",
      "pageId": "light-work-experience",
      "imageId": "1sscgz1N9nbxrjwJrWpZ41V5T8HzXj-he",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1sscgz1N9nbxrjwJrWpZ41V5T8HzXj-he&sz=w800",
      "caption": "開店前爭取時間理貨",
      "order": 1009,
      "published": true
    },
    {
      "id": "light-work-experience-1NFWpTgq8REWpVc9EeOYcr6qHwCz6IzxP",
      "pageId": "light-work-experience",
      "imageId": "1NFWpTgq8REWpVc9EeOYcr6qHwCz6IzxP",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1NFWpTgq8REWpVc9EeOYcr6qHwCz6IzxP&sz=w800",
      "caption": "專心聆聽負責人講解店務員職責",
      "order": 1010,
      "published": true
    },
    {
      "id": "light-work-experience-1xJsTcO9mOn5Xz_ruazNXBVEUXDAGy7H-",
      "pageId": "light-work-experience",
      "imageId": "1xJsTcO9mOn5Xz_ruazNXBVEUXDAGy7H-",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1xJsTcO9mOn5Xz_ruazNXBVEUXDAGy7H-&sz=w800",
      "caption": "向客人介紹自家製品",
      "order": 1011,
      "published": true
    },
    {
      "id": "moderate-cleaning-1n_Ja1oCZAAjonUoAcktP4U1IqUimQCsd",
      "pageId": "moderate-cleaning",
      "imageId": "1n_Ja1oCZAAjonUoAcktP4U1IqUimQCsd",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1n_Ja1oCZAAjonUoAcktP4U1IqUimQCsd&sz=w800",
      "caption": "於CAFÉ午膳營運期間帶學生實習洗碗 (9)",
      "order": 1000,
      "published": true
    },
    {
      "id": "moderate-cleaning-1p50zAJ7jnEX1JgpFb-CZhdc1yF5SJ-d5",
      "pageId": "moderate-cleaning",
      "imageId": "1p50zAJ7jnEX1JgpFb-CZhdc1yF5SJ-d5",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1p50zAJ7jnEX1JgpFb-CZhdc1yF5SJ-d5&sz=w800",
      "caption": "於CAFÉ午膳營運期間帶學生實習洗碗 (8)",
      "order": 1001,
      "published": true
    },
    {
      "id": "moderate-cleaning-1TnyFg1makhWqHey3OQOTCj_CFCcMtfmM",
      "pageId": "moderate-cleaning",
      "imageId": "1TnyFg1makhWqHey3OQOTCj_CFCcMtfmM",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1TnyFg1makhWqHey3OQOTCj_CFCcMtfmM&sz=w800",
      "caption": "於CAFÉ午膳營運期間帶學生實習洗碗 (7)",
      "order": 1002,
      "published": true
    },
    {
      "id": "moderate-cleaning-1_RhRTjehcM2TSQY7KhQujvOEtEAbrwaf",
      "pageId": "moderate-cleaning",
      "imageId": "1_RhRTjehcM2TSQY7KhQujvOEtEAbrwaf",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1_RhRTjehcM2TSQY7KhQujvOEtEAbrwaf&sz=w800",
      "caption": "於CAFÉ午膳營運期間帶學生實習洗碗 (6)",
      "order": 1003,
      "published": true
    },
    {
      "id": "moderate-cleaning-11rPgCYGWTNeHTbGYJQ6xynteIwN5VR2f",
      "pageId": "moderate-cleaning",
      "imageId": "11rPgCYGWTNeHTbGYJQ6xynteIwN5VR2f",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=11rPgCYGWTNeHTbGYJQ6xynteIwN5VR2f&sz=w800",
      "caption": "於CAFÉ午膳營運期間帶學生實習洗碗 (5)",
      "order": 1004,
      "published": true
    },
    {
      "id": "moderate-cleaning-1sOcaDDfYdL2HIStRdNzXCOGOoxwDX2Xw",
      "pageId": "moderate-cleaning",
      "imageId": "1sOcaDDfYdL2HIStRdNzXCOGOoxwDX2Xw",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1sOcaDDfYdL2HIStRdNzXCOGOoxwDX2Xw&sz=w800",
      "caption": "於CAFÉ午膳營運期間帶學生實習洗碗 (4)",
      "order": 1005,
      "published": true
    },
    {
      "id": "moderate-cleaning-1RcSYzMeJ77vWhL6VLSM749YSL6A34hYI",
      "pageId": "moderate-cleaning",
      "imageId": "1RcSYzMeJ77vWhL6VLSM749YSL6A34hYI",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1RcSYzMeJ77vWhL6VLSM749YSL6A34hYI&sz=w800",
      "caption": "於CAFÉ午膳營運期間帶學生實習洗碗 (3)",
      "order": 1006,
      "published": true
    },
    {
      "id": "moderate-cleaning-1nzkyCH_A-A6H4XYhAxYTMLoVQ32r2caK",
      "pageId": "moderate-cleaning",
      "imageId": "1nzkyCH_A-A6H4XYhAxYTMLoVQ32r2caK",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1nzkyCH_A-A6H4XYhAxYTMLoVQ32r2caK&sz=w800",
      "caption": "於CAFÉ午膳營運期間帶學生實習洗碗 (1)",
      "order": 1007,
      "published": true
    },
    {
      "id": "moderate-planting-1a7i3wb-PikERII9OJQya9Z2aKI8FU1Id",
      "pageId": "moderate-planting",
      "imageId": "1a7i3wb-PikERII9OJQya9Z2aKI8FU1Id",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1a7i3wb-PikERII9OJQya9Z2aKI8FU1Id&sz=w800",
      "caption": "尚cafe裝飾植物 (2)",
      "order": 1000,
      "published": true
    },
    {
      "id": "moderate-planting-1wpT9cDsdVSL3AtvNr_Cv6KJkFAOaIplE",
      "pageId": "moderate-planting",
      "imageId": "1wpT9cDsdVSL3AtvNr_Cv6KJkFAOaIplE",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1wpT9cDsdVSL3AtvNr_Cv6KJkFAOaIplE&sz=w800",
      "caption": "尚cafe裝飾植物",
      "order": 1001,
      "published": true
    },
    {
      "id": "moderate-planting-1KvjS-jC_YYLKJ6vosVrFsI4dN_DHtZpY",
      "pageId": "moderate-planting",
      "imageId": "1KvjS-jC_YYLKJ6vosVrFsI4dN_DHtZpY",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1KvjS-jC_YYLKJ6vosVrFsI4dN_DHtZpY&sz=w800",
      "caption": "種植成果 (2)",
      "order": 1002,
      "published": true
    },
    {
      "id": "moderate-planting-1LMktGBbVejx0YMxcphAyTlW7IbVqk-x2",
      "pageId": "moderate-planting",
      "imageId": "1LMktGBbVejx0YMxcphAyTlW7IbVqk-x2",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1LMktGBbVejx0YMxcphAyTlW7IbVqk-x2&sz=w800",
      "caption": "種植成果",
      "order": 1003,
      "published": true
    },
    {
      "id": "moderate-planting-15QQaWF_WDQlOu0RHAMaafNhwnOVJP9Qg",
      "pageId": "moderate-planting",
      "imageId": "15QQaWF_WDQlOu0RHAMaafNhwnOVJP9Qg",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=15QQaWF_WDQlOu0RHAMaafNhwnOVJP9Qg&sz=w800",
      "caption": "養護食用花 (2)",
      "order": 1004,
      "published": true
    },
    {
      "id": "moderate-planting-1dXlVvswg7baonRq9ef7Sc8Cei7_tlSis",
      "pageId": "moderate-planting",
      "imageId": "1dXlVvswg7baonRq9ef7Sc8Cei7_tlSis",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1dXlVvswg7baonRq9ef7Sc8Cei7_tlSis&sz=w800",
      "caption": "養護食用花",
      "order": 1005,
      "published": true
    },
    {
      "id": "moderate-planting-1Hv2BJgelAjqhDb4YSXwVylmxWG1ra5o3",
      "pageId": "moderate-planting",
      "imageId": "1Hv2BJgelAjqhDb4YSXwVylmxWG1ra5o3",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1Hv2BJgelAjqhDb4YSXwVylmxWG1ra5o3&sz=w800",
      "caption": "種植食用花 (2)",
      "order": 1006,
      "published": true
    },
    {
      "id": "moderate-planting-1GxqMROUqswJcKTchl3YdWOHjjvEUvR-B",
      "pageId": "moderate-planting",
      "imageId": "1GxqMROUqswJcKTchl3YdWOHjjvEUvR-B",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1GxqMROUqswJcKTchl3YdWOHjjvEUvR-B&sz=w800",
      "caption": "採收食用花 (2)",
      "order": 1007,
      "published": true
    },
    {
      "id": "moderate-planting-1sSObT7jIj8RJpOgBtir3GdVe5hVcw0HC",
      "pageId": "moderate-planting",
      "imageId": "1sSObT7jIj8RJpOgBtir3GdVe5hVcw0HC",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1sSObT7jIj8RJpOgBtir3GdVe5hVcw0HC&sz=w800",
      "caption": "採收食用花",
      "order": 1008,
      "published": true
    },
    {
      "id": "moderate-planting-18_l9wAkTvd2zWuX970K-H3_L-1aXSzIi",
      "pageId": "moderate-planting",
      "imageId": "18_l9wAkTvd2zWuX970K-H3_L-1aXSzIi",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=18_l9wAkTvd2zWuX970K-H3_L-1aXSzIi&sz=w800",
      "caption": "IMG_0695",
      "order": 1009,
      "published": true
    },
    {
      "id": "moderate-planting-19A8BmQM-drAks8fRvQ-sblhJCjulcSpO",
      "pageId": "moderate-planting",
      "imageId": "19A8BmQM-drAks8fRvQ-sblhJCjulcSpO",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=19A8BmQM-drAks8fRvQ-sblhJCjulcSpO&sz=w800",
      "caption": "IMG_0492",
      "order": 1010,
      "published": true
    },
    {
      "id": "moderate-planting-1zzrO3WPWXwOvwyVgsH820G8NwaR7eu_b",
      "pageId": "moderate-planting",
      "imageId": "1zzrO3WPWXwOvwyVgsH820G8NwaR7eu_b",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1zzrO3WPWXwOvwyVgsH820G8NwaR7eu_b&sz=w800",
      "caption": "IMG_0741",
      "order": 1011,
      "published": true
    },
    {
      "id": "moderate-art-development-14fnL_Kq5mhZEa3BQD2-nQykkwAeRWirr",
      "pageId": "moderate-art-development",
      "imageId": "14fnL_Kq5mhZEa3BQD2-nQykkwAeRWirr",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=14fnL_Kq5mhZEa3BQD2-nQykkwAeRWirr&sz=w800",
      "caption": "IMG_8241",
      "order": 1000,
      "published": true
    },
    {
      "id": "moderate-art-development-15376X3qFuVehghIoaoAnBxj0uMKaC9dc",
      "pageId": "moderate-art-development",
      "imageId": "15376X3qFuVehghIoaoAnBxj0uMKaC9dc",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=15376X3qFuVehghIoaoAnBxj0uMKaC9dc&sz=w800",
      "caption": "IMG_9582",
      "order": 1001,
      "published": true
    },
    {
      "id": "moderate-art-development-1w9mmGkcNlt7OpaObzJuL4DrpyiuHzOHP",
      "pageId": "moderate-art-development",
      "imageId": "1w9mmGkcNlt7OpaObzJuL4DrpyiuHzOHP",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1w9mmGkcNlt7OpaObzJuL4DrpyiuHzOHP&sz=w800",
      "caption": "IMG_5585",
      "order": 1002,
      "published": true
    },
    {
      "id": "moderate-art-development-1fcBVN-GtorhdUPTZ5B2WA_dJiEneXCLl",
      "pageId": "moderate-art-development",
      "imageId": "1fcBVN-GtorhdUPTZ5B2WA_dJiEneXCLl",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1fcBVN-GtorhdUPTZ5B2WA_dJiEneXCLl&sz=w800",
      "caption": "IMG_5577",
      "order": 1003,
      "published": true
    },
    {
      "id": "moderate-art-development-1DpxCXi2AHR33vuMDhy3P5_GmIAKsMaCL",
      "pageId": "moderate-art-development",
      "imageId": "1DpxCXi2AHR33vuMDhy3P5_GmIAKsMaCL",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1DpxCXi2AHR33vuMDhy3P5_GmIAKsMaCL&sz=w800",
      "caption": "IMG_5231",
      "order": 1004,
      "published": true
    },
    {
      "id": "moderate-art-development-1mIiNwaLdxhJIDfzpDZ6kIIGHiLj4PvCy",
      "pageId": "moderate-art-development",
      "imageId": "1mIiNwaLdxhJIDfzpDZ6kIIGHiLj4PvCy",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1mIiNwaLdxhJIDfzpDZ6kIIGHiLj4PvCy&sz=w800",
      "caption": "IMG_5230",
      "order": 1005,
      "published": true
    },
    {
      "id": "moderate-community-exploration-1nLrZBj-90l_P2nw3Yk9N3VGlHKFlCELN",
      "pageId": "moderate-community-exploration",
      "imageId": "1nLrZBj-90l_P2nw3Yk9N3VGlHKFlCELN",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1nLrZBj-90l_P2nw3Yk9N3VGlHKFlCELN&sz=w800",
      "caption": "IMG_8524",
      "order": 1000,
      "published": true
    },
    {
      "id": "moderate-community-exploration-18ae15PmIINSJFqdJdE3fmPO8uAG1USJe",
      "pageId": "moderate-community-exploration",
      "imageId": "18ae15PmIINSJFqdJdE3fmPO8uAG1USJe",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=18ae15PmIINSJFqdJdE3fmPO8uAG1USJe&sz=w800",
      "caption": "IMG_6307",
      "order": 1001,
      "published": true
    },
    {
      "id": "moderate-community-exploration-1j1_MJcZhFGYceQ9-tVXur9cQDweyZF2R",
      "pageId": "moderate-community-exploration",
      "imageId": "1j1_MJcZhFGYceQ9-tVXur9cQDweyZF2R",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1j1_MJcZhFGYceQ9-tVXur9cQDweyZF2R&sz=w800",
      "caption": "IMG_6306",
      "order": 1002,
      "published": true
    },
    {
      "id": "moderate-community-exploration-1cak3XG4P7uzpv3uuFit9imYoY8PlWCmS",
      "pageId": "moderate-community-exploration",
      "imageId": "1cak3XG4P7uzpv3uuFit9imYoY8PlWCmS",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1cak3XG4P7uzpv3uuFit9imYoY8PlWCmS&sz=w800",
      "caption": "IMG_6292",
      "order": 1003,
      "published": true
    },
    {
      "id": "moderate-community-exploration-1PLMqMmFvEaSjoVIl6m6nN8RRqFY-sfFD",
      "pageId": "moderate-community-exploration",
      "imageId": "1PLMqMmFvEaSjoVIl6m6nN8RRqFY-sfFD",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1PLMqMmFvEaSjoVIl6m6nN8RRqFY-sfFD&sz=w800",
      "caption": "IMG_6273",
      "order": 1004,
      "published": true
    },
    {
      "id": "moderate-independent-living-1DYqWoaHHuVtIkU7VgqiH-6Ki19m7l-NE",
      "pageId": "moderate-independent-living",
      "imageId": "1DYqWoaHHuVtIkU7VgqiH-6Ki19m7l-NE",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1DYqWoaHHuVtIkU7VgqiH-6Ki19m7l-NE&sz=w800",
      "caption": "學生於個人成長課學習製作三文治 (11)",
      "order": 1000,
      "published": true
    },
    {
      "id": "moderate-independent-living-1SdOLdnMSeUZiTG-tyAx2MQ-2Wip7S8zB",
      "pageId": "moderate-independent-living",
      "imageId": "1SdOLdnMSeUZiTG-tyAx2MQ-2Wip7S8zB",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1SdOLdnMSeUZiTG-tyAx2MQ-2Wip7S8zB&sz=w800",
      "caption": "學生於個人成長課學習製作三文治 (9)",
      "order": 1001,
      "published": true
    },
    {
      "id": "moderate-independent-living-1cRgCV13cSoR8ZPR9i79wptAeJBSZHds2",
      "pageId": "moderate-independent-living",
      "imageId": "1cRgCV13cSoR8ZPR9i79wptAeJBSZHds2",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1cRgCV13cSoR8ZPR9i79wptAeJBSZHds2&sz=w800",
      "caption": "學生於個人成長課學習製作三文治 (10)",
      "order": 1002,
      "published": true
    },
    {
      "id": "moderate-independent-living-1T0Ol0sHOO3Wc-d8VTfSair3PruXVARF5",
      "pageId": "moderate-independent-living",
      "imageId": "1T0Ol0sHOO3Wc-d8VTfSair3PruXVARF5",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1T0Ol0sHOO3Wc-d8VTfSair3PruXVARF5&sz=w800",
      "caption": "學生於個人成長課學習製作三文治 (8)",
      "order": 1003,
      "published": true
    },
    {
      "id": "moderate-independent-living-11GFW3gdoK5Oz2dFSzJfgExAxvuV9Ie56",
      "pageId": "moderate-independent-living",
      "imageId": "11GFW3gdoK5Oz2dFSzJfgExAxvuV9Ie56",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=11GFW3gdoK5Oz2dFSzJfgExAxvuV9Ie56&sz=w800",
      "caption": "學生於個人成長課學習製作吞拿魚餅乾",
      "order": 1004,
      "published": true
    },
    {
      "id": "moderate-independent-living-1jW03ZPzbkLhvmR5D-5HUypR_5UpKT0Y7",
      "pageId": "moderate-independent-living",
      "imageId": "1jW03ZPzbkLhvmR5D-5HUypR_5UpKT0Y7",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1jW03ZPzbkLhvmR5D-5HUypR_5UpKT0Y7&sz=w800",
      "caption": "學生於個人成長課學習製作三文治 (7)",
      "order": 1005,
      "published": true
    },
    {
      "id": "moderate-independent-living-1yoG1ywsmk0io7-gSbWncwYFWgHLhlWLi",
      "pageId": "moderate-independent-living",
      "imageId": "1yoG1ywsmk0io7-gSbWncwYFWgHLhlWLi",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1yoG1ywsmk0io7-gSbWncwYFWgHLhlWLi&sz=w800",
      "caption": "學生於個人成長課學習製作三文治 (6)",
      "order": 1006,
      "published": true
    },
    {
      "id": "moderate-independent-living-1CTEwGQxGz-GBDL4PDYZKLlJbf9aqOMf7",
      "pageId": "moderate-independent-living",
      "imageId": "1CTEwGQxGz-GBDL4PDYZKLlJbf9aqOMf7",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1CTEwGQxGz-GBDL4PDYZKLlJbf9aqOMf7&sz=w800",
      "caption": "學生於個人成長課學習製作三文治 (2)",
      "order": 1007,
      "published": true
    },
    {
      "id": "moderate-independent-living-1YnXriPOeYn5pZemUj_8kGlz4ve4YFS6o",
      "pageId": "moderate-independent-living",
      "imageId": "1YnXriPOeYn5pZemUj_8kGlz4ve4YFS6o",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1YnXriPOeYn5pZemUj_8kGlz4ve4YFS6o&sz=w800",
      "caption": "學生於個人成長課學習製作三文治 (1)",
      "order": 1008,
      "published": true
    },
    {
      "id": "moderate-independent-living-1GQg7ujZThY3vl8f2Fz-wn6zLah25C2Qf",
      "pageId": "moderate-independent-living",
      "imageId": "1GQg7ujZThY3vl8f2Fz-wn6zLah25C2Qf",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1GQg7ujZThY3vl8f2Fz-wn6zLah25C2Qf&sz=w800",
      "caption": "學生於個人成長課學習製作三文治 (5)",
      "order": 1009,
      "published": true
    },
    {
      "id": "moderate-independent-living-180G_VlSlRgYxTcSXEBUIQQJCfQ0q82NA",
      "pageId": "moderate-independent-living",
      "imageId": "180G_VlSlRgYxTcSXEBUIQQJCfQ0q82NA",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=180G_VlSlRgYxTcSXEBUIQQJCfQ0q82NA&sz=w800",
      "caption": "學生於個人成長課學習製作三文治 (4)",
      "order": 1010,
      "published": true
    },
    {
      "id": "moderate-independent-living-1JsqYa1UwxiZPIMVROoH0whTHNvB-jz4c",
      "pageId": "moderate-independent-living",
      "imageId": "1JsqYa1UwxiZPIMVROoH0whTHNvB-jz4c",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1JsqYa1UwxiZPIMVROoH0whTHNvB-jz4c&sz=w800",
      "caption": "學生於個人成長課學習製作三文治 (3)",
      "order": 1011,
      "published": true
    },
    {
      "id": "moderate-work-experience-1Ns-Yoz1VL-KLu1ye6iJfYxh2gmVUzFfG",
      "pageId": "moderate-work-experience",
      "imageId": "1Ns-Yoz1VL-KLu1ye6iJfYxh2gmVUzFfG",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1Ns-Yoz1VL-KLu1ye6iJfYxh2gmVUzFfG&sz=w800",
      "caption": "學生在本校宿舍職員指導下進行清潔宿舍工作",
      "order": 1000,
      "published": true
    },
    {
      "id": "moderate-work-experience-1tfBQyrzS-QIhMKsISf3JyFUkVffb-osG",
      "pageId": "moderate-work-experience",
      "imageId": "1tfBQyrzS-QIhMKsISf3JyFUkVffb-osG",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1tfBQyrzS-QIhMKsISf3JyFUkVffb-osG&sz=w800",
      "caption": "學生正進行「旅行衛生包」包裝工作訓練",
      "order": 1001,
      "published": true
    },
    {
      "id": "moderate-work-experience-1ukT8NI9lBNOHxVJye0cSOIrG0OljgnnR",
      "pageId": "moderate-work-experience",
      "imageId": "1ukT8NI9lBNOHxVJye0cSOIrG0OljgnnR",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1ukT8NI9lBNOHxVJye0cSOIrG0OljgnnR&sz=w800",
      "caption": "學生在友校樂進學校教職員指導下進行分配午膳的工作",
      "order": 1002,
      "published": true
    },
    {
      "id": "moderate-personal-growth-1nQcLCOzr1Y9ojy5SsjXEHd-vUSBZ29oM",
      "pageId": "moderate-personal-growth",
      "imageId": "1nQcLCOzr1Y9ojy5SsjXEHd-vUSBZ29oM",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1nQcLCOzr1Y9ojy5SsjXEHd-vUSBZ29oM&sz=w800",
      "caption": "團體合作：飛標",
      "order": 1000,
      "published": true
    },
    {
      "id": "moderate-personal-growth-1nrdKKjN3obCk0SaEnuDqe8r4E576wD4z",
      "pageId": "moderate-personal-growth",
      "imageId": "1nrdKKjN3obCk0SaEnuDqe8r4E576wD4z",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1nrdKKjN3obCk0SaEnuDqe8r4E576wD4z&sz=w800",
      "caption": "團體合作：運球",
      "order": 1001,
      "published": true
    },
    {
      "id": "moderate-personal-growth-1d4QGgVf8pGPGFLe1HF7qIb9jQGxFgjGM",
      "pageId": "moderate-personal-growth",
      "imageId": "1d4QGgVf8pGPGFLe1HF7qIb9jQGxFgjGM",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1d4QGgVf8pGPGFLe1HF7qIb9jQGxFgjGM&sz=w800",
      "caption": "團體合作：飛標 (1)",
      "order": 1002,
      "published": true
    },
    {
      "id": "moderate-personal-growth-1AitKj7jTn_py7QKugafP1xnmHZ1M2idW",
      "pageId": "moderate-personal-growth",
      "imageId": "1AitKj7jTn_py7QKugafP1xnmHZ1M2idW",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1AitKj7jTn_py7QKugafP1xnmHZ1M2idW&sz=w800",
      "caption": "團體合作：互相傳球",
      "order": 1003,
      "published": true
    },
    {
      "id": "moderate-personal-growth-1Tr7Yhz6STfJKUgNyOlXzFg5HZt95H3VI",
      "pageId": "moderate-personal-growth",
      "imageId": "1Tr7Yhz6STfJKUgNyOlXzFg5HZt95H3VI",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1Tr7Yhz6STfJKUgNyOlXzFg5HZt95H3VI&sz=w800",
      "caption": "團體合作：齊心協力",
      "order": 1004,
      "published": true
    },
    {
      "id": "moderate-personal-growth-1hyFtbQrnly6_ixEg-qQvRMwJR1ttrSWG",
      "pageId": "moderate-personal-growth",
      "imageId": "1hyFtbQrnly6_ixEg-qQvRMwJR1ttrSWG",
      "thumbnailUrl": "https://drive.google.com/thumbnail?id=1hyFtbQrnly6_ixEg-qQvRMwJR1ttrSWG&sz=w800",
      "caption": "團體合作：風火輪",
      "order": 1005,
      "published": true
    }
  ]
};
